.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-alias \- Create command shortcuts


.SH SYNOPSIS
.PP
\fBgh alias  [flags]\fP


.SH DESCRIPTION
.PP
Aliases can be used to make shortcuts for gh commands or to compose multiple commands.

.PP
Run "gh help alias set" to learn more.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh(1)\fP, \fBgh\-alias\-delete(1)\fP, \fBgh\-alias\-list(1)\fP, \fBgh\-alias\-set(1)\fP
