.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-auth \- Login, logout, and refresh your authentication


.SH SYNOPSIS
.PP
\fBgh auth  [flags]\fP


.SH DESCRIPTION
.PP
Manage gh's authentication state.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh(1)\fP, \fBgh\-auth\-login(1)\fP, \fBgh\-auth\-logout(1)\fP, \fBgh\-auth\-refresh(1)\fP, \fBgh\-auth\-status(1)\fP
