.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-alias\-list \- List your aliases


.SH SYNOPSIS
.PP
\fBgh alias list [flags]\fP


.SH DESCRIPTION
.PP
This command prints out all of the aliases gh is configured to use.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh\-alias(1)\fP
