.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-alias\-delete \- Delete an alias


.SH SYNOPSIS
.PP
\fBgh alias delete  [flags]\fP


.SH DESCRIPTION
.PP
Delete an alias


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh\-alias(1)\fP
