.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-gist\-edit \- Edit one of your gists


.SH SYNOPSIS
.PP
\fBgh gist edit { | } [flags]\fP


.SH DESCRIPTION
.PP
Edit one of your gists


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-filename\fP=""
	Select a file to edit


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh\-gist(1)\fP
