.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-gist\-delete \- Delete a gist


.SH SYNOPSIS
.PP
\fBgh gist delete { | } [flags]\fP


.SH DESCRIPTION
.PP
Delete a gist


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh\-gist(1)\fP
