.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-gist \- Manage gists


.SH SYNOPSIS
.PP
\fBgh gist  [flags]\fP


.SH DESCRIPTION
.PP
Work with GitHub gists.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh(1)\fP, \fBgh\-gist\-clone(1)\fP, \fBgh\-gist\-create(1)\fP, \fBgh\-gist\-delete(1)\fP, \fBgh\-gist\-edit(1)\fP, \fBgh\-gist\-list(1)\fP, \fBgh\-gist\-view(1)\fP
