.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-gist\-list \- List your gists


.SH SYNOPSIS
.PP
\fBgh gist list [flags]\fP


.SH DESCRIPTION
.PP
List your gists


.SH OPTIONS
.PP
\fB\-L\fP, \fB\-\-limit\fP=10
	Maximum number of gists to fetch

.PP
\fB\-\-public\fP[=false]
	Show only public gists

.PP
\fB\-\-secret\fP[=false]
	Show only secret gists


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh\-gist(1)\fP
