.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-gist\-view \- View a gist


.SH SYNOPSIS
.PP
\fBgh gist view { | } [flags]\fP


.SH DESCRIPTION
.PP
View a gist


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-filename\fP=""
	Display a single file from the gist

.PP
\fB\-\-files\fP[=false]
	List file names from the gist

.PP
\fB\-r\fP, \fB\-\-raw\fP[=false]
	Print raw instead of rendered gist contents

.PP
\fB\-w\fP, \fB\-\-web\fP[=false]
	Open gist in the browser


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh\-gist(1)\fP
