.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-issue\-edit \- Edit an issue


.SH SYNOPSIS
.PP
\fBgh issue edit { | } [flags]\fP


.SH DESCRIPTION
.PP
Edit an issue


.SH OPTIONS
.PP
\fB\-\-add\-assignee\fP=[]
	Add assigned users by their \fB\fClogin\fR\&. Use "@me" to assign yourself.

.PP
\fB\-\-add\-label\fP=[]
	Add labels by \fB\fCname\fR

.PP
\fB\-\-add\-project\fP=[]
	Add the issue to projects by \fB\fCname\fR

.PP
\fB\-b\fP, \fB\-\-body\fP=""
	Set the new body.

.PP
\fB\-m\fP, \fB\-\-milestone\fP=""
	Edit the milestone the issue belongs to by \fB\fCname\fR

.PP
\fB\-\-remove\-assignee\fP=[]
	Remove assigned users by their \fB\fClogin\fR\&. Use "@me" to unassign yourself.

.PP
\fB\-\-remove\-label\fP=[]
	Remove labels by \fB\fCname\fR

.PP
\fB\-\-remove\-project\fP=[]
	Remove the issue from projects by \fB\fCname\fR

.PP
\fB\-t\fP, \fB\-\-title\fP=""
	Set the new title.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH EXAMPLE
.PP
.RS

.nf
$ gh issue edit 23 \-\-title "I found a bug" \-\-body "Nothing works"
$ gh issue edit 23 \-\-add\-label "bug,help wanted" \-\-remove\-label "core"
$ gh issue edit 23 \-\-add\-assignee @me \-\-remove\-assignee monalisa,hubot
$ gh issue edit 23 \-\-add\-project "Roadmap" \-\-remove\-project v1,v2
$ gh issue edit 23 \-\-milestone "Version 1"


.fi
.RE


.SH SEE ALSO
.PP
\fBgh\-issue(1)\fP
