.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-issue\-view \- View an issue


.SH SYNOPSIS
.PP
\fBgh issue view { | } [flags]\fP


.SH DESCRIPTION
.PP
Display the title, body, and other information about an issue.

.PP
With '\-\-web', open the issue in a web browser instead.


.SH OPTIONS
.PP
\fB\-c\fP, \fB\-\-comments\fP[=false]
	View issue comments

.PP
\fB\-w\fP, \fB\-\-web\fP[=false]
	Open an issue in the browser


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH SEE ALSO
.PP
\fBgh\-issue(1)\fP
