.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-issue\-list \- List and filter issues in this repository


.SH SYNOPSIS
.PP
\fBgh issue list [flags]\fP


.SH DESCRIPTION
.PP
List and filter issues in this repository


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-assignee\fP=""
	Filter by assignee

.PP
\fB\-A\fP, \fB\-\-author\fP=""
	Filter by author

.PP
\fB\-l\fP, \fB\-\-label\fP=[]
	Filter by labels

.PP
\fB\-L\fP, \fB\-\-limit\fP=30
	Maximum number of issues to fetch

.PP
\fB\-\-mention\fP=""
	Filter by mention

.PP
\fB\-m\fP, \fB\-\-milestone\fP=""
	Filter by milestone \fB\fCnumber\fR or \fB\fCtitle\fR

.PP
\fB\-s\fP, \fB\-\-state\fP="open"
	Filter by state: {open|closed|all}

.PP
\fB\-w\fP, \fB\-\-web\fP[=false]
	Open the browser to list the issue(s)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH EXAMPLE
.PP
.RS

.nf
$ gh issue list \-l "help wanted"
$ gh issue list \-A monalisa
$ gh issue list \-a @me
$ gh issue list \-\-web
$ gh issue list \-\-milestone 'MVP'


.fi
.RE


.SH SEE ALSO
.PP
\fBgh\-issue(1)\fP
