.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-pr\-view \- View a pull request


.SH SYNOPSIS
.PP
\fBgh pr view [ |  | ] [flags]\fP


.SH DESCRIPTION
.PP
Display the title, body, and other information about a pull request.

.PP
Without an argument, the pull request that belongs to the current branch
is displayed.

.PP
With '\-\-web', open the pull request in a web browser instead.


.SH OPTIONS
.PP
\fB\-c\fP, \fB\-\-comments\fP[=false]
	View pull request comments

.PP
\fB\-w\fP, \fB\-\-web\fP[=false]
	Open a pull request in the browser


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH SEE ALSO
.PP
\fBgh\-pr(1)\fP
