.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-pr\-diff \- View changes in a pull request


.SH SYNOPSIS
.PP
\fBgh pr diff [ |  | ] [flags]\fP


.SH DESCRIPTION
.PP
View changes in a pull request


.SH OPTIONS
.PP
\fB\-\-color\fP="auto"
	Use color in diff output: {always|never|auto}


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH SEE ALSO
.PP
\fBgh\-pr(1)\fP
