.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-pr\-ready \- Mark a pull request as ready for review


.SH SYNOPSIS
.PP
\fBgh pr ready [ |  | ] [flags]\fP


.SH DESCRIPTION
.PP
Mark a pull request as ready for review


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH SEE ALSO
.PP
\fBgh\-pr(1)\fP
