.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-pr\-close \- Close a pull request


.SH SYNOPSIS
.PP
\fBgh pr close { |  | } [flags]\fP


.SH DESCRIPTION
.PP
Close a pull request


.SH OPTIONS
.PP
\fB\-d\fP, \fB\-\-delete\-branch\fP[=false]
	Delete the local and remote branch after close


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH SEE ALSO
.PP
\fBgh\-pr(1)\fP
