.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-repo\-fork \- Create a fork of a repository


.SH SYNOPSIS
.PP
\fBgh repo fork [] [\-\- \&...] [flags]\fP


.SH DESCRIPTION
.PP
Create a fork of a repository.

.PP
With no argument, creates a fork of the current repository. Otherwise, forks
the specified repository.

.PP
By default, the new fork is set to be your 'origin' remote and any existing
origin remote is renamed to 'upstream'. To alter this behavior, you can set
a name for the new fork's remote with \-\-remote\-name.

.PP
Additional 'git clone' flags can be passed in by listing them after '\-\-'.


.SH OPTIONS
.PP
\fB\-\-clone\fP[=false]
	Clone the fork {true|false}

.PP
\fB\-\-remote\fP[=false]
	Add remote for fork {true|false}

.PP
\fB\-\-remote\-name\fP="origin"
	Specify a name for a fork's new remote.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh\-repo(1)\fP
