.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-release\-view \- View information about a release


.SH SYNOPSIS
.PP
\fBgh release view [] [flags]\fP


.SH DESCRIPTION
.PP
View information about a GitHub Release.

.PP
Without an explicit tag name argument, the latest release in the project
is shown.


.SH OPTIONS
.PP
\fB\-w\fP, \fB\-\-web\fP[=false]
	Open the release in the browser


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH SEE ALSO
.PP
\fBgh\-release(1)\fP
