.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-release \- Manage GitHub releases


.SH SYNOPSIS
.PP
\fBgh release  [flags]\fP


.SH DESCRIPTION
.PP
Manage GitHub releases


.SH OPTIONS
.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh(1)\fP, \fBgh\-release\-create(1)\fP, \fBgh\-release\-delete(1)\fP, \fBgh\-release\-download(1)\fP, \fBgh\-release\-list(1)\fP, \fBgh\-release\-upload(1)\fP, \fBgh\-release\-view(1)\fP
