.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-release\-list \- List releases in a repository


.SH SYNOPSIS
.PP
\fBgh release list [flags]\fP


.SH DESCRIPTION
.PP
List releases in a repository


.SH OPTIONS
.PP
\fB\-L\fP, \fB\-\-limit\fP=30
	Maximum number of items to fetch


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH SEE ALSO
.PP
\fBgh\-release(1)\fP
