.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-release\-upload \- Upload assets to a release


.SH SYNOPSIS
.PP
\fBgh release upload  \&... [flags]\fP


.SH DESCRIPTION
.PP
Upload asset files to a GitHub Release.

.PP
To define a display label for an asset, append text starting with '#' after the
file name.


.SH OPTIONS
.PP
\fB\-\-clobber\fP[=false]
	Overwrite existing assets of the same name


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH SEE ALSO
.PP
\fBgh\-release(1)\fP
