.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-repo \- Create, clone, fork, and view repositories


.SH SYNOPSIS
.PP
\fBgh repo  [flags]\fP


.SH DESCRIPTION
.PP
Work with GitHub repositories


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH EXAMPLE
.PP
.RS

.nf
$ gh repo create
$ gh repo clone cli/cli
$ gh repo view \-\-web


.fi
.RE


.SH SEE ALSO
.PP
\fBgh(1)\fP, \fBgh\-repo\-clone(1)\fP, \fBgh\-repo\-create(1)\fP, \fBgh\-repo\-fork(1)\fP, \fBgh\-repo\-view(1)\fP
