.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-secret\-set \- Create or update secrets


.SH SYNOPSIS
.PP
\fBgh secret set  [flags]\fP


.SH DESCRIPTION
.PP
Locally encrypt a new or updated secret at either the repository or organization level and send it to GitHub for storage.


.SH OPTIONS
.PP
\fB\-b\fP, \fB\-\-body\fP=""
	A value for the secret. Reads from STDIN if not specified.

.PP
\fB\-o\fP, \fB\-\-org\fP=""
	List secrets for an organization

.PP
\fB\-r\fP, \fB\-\-repos\fP=[]
	List of repository names for \fB\fCselected\fR visibility

.PP
\fB\-v\fP, \fB\-\-visibility\fP="private"
	Set visibility for an organization secret: \fB\fCall\fR, \fB\fCprivate\fR, or \fB\fCselected\fR


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH EXAMPLE
.PP
.RS

.nf
$ gh secret set FROM\_FLAG  \-b"some literal value"
$ gh secret set FROM\_ENV  \-b"${ENV\_VALUE}"
$ gh secret set FROM\_FILE < file.json
$ gh secret set ORG\_SECRET \-bval \-\-org=anOrg \-\-visibility=all
$ gh secret set ORG\_SECRET \-bval \-\-org=anOrg \-\-repos="repo1,repo2,repo3"


.fi
.RE


.SH SEE ALSO
.PP
\fBgh\-secret(1)\fP
