.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-secret \- Manage GitHub secrets


.SH SYNOPSIS
.PP
\fBgh secret  [flags]\fP


.SH DESCRIPTION
.PP
Secrets can be set at the repository or organization level for use in GitHub Actions.
Run "gh help secret set" to learn how to get started.


.SH OPTIONS
.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh(1)\fP, \fBgh\-secret\-list(1)\fP, \fBgh\-secret\-remove(1)\fP, \fBgh\-secret\-set(1)\fP
