.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-ssh\-key\-add \- Add an SSH key to your GitHub account


.SH SYNOPSIS
.PP
\fBgh ssh\-key add [] [flags]\fP


.SH DESCRIPTION
.PP
Add an SSH key to your GitHub account


.SH OPTIONS
.PP
\fB\-t\fP, \fB\-\-title\fP=""
	Title for the new key


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh\-ssh\-key(1)\fP
