.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh\-secret\-list \- List secrets


.SH SYNOPSIS
.PP
\fBgh secret list [flags]\fP


.SH DESCRIPTION
.PP
List secrets for a repository or organization


.SH OPTIONS
.PP
\fB\-o\fP, \fB\-\-org\fP=""
	List secrets for an organization


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH SEE ALSO
.PP
\fBgh\-secret(1)\fP
