.nh
.TH "gh" "1" "Feb 2021" "" ""

.SH NAME
.PP
gh \- GitHub CLI


.SH SYNOPSIS
.PP
\fBgh   [flags]\fP


.SH DESCRIPTION
.PP
Work seamlessly with GitHub from the command line.


.SH OPTIONS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-\-version\fP[=false]
	Show gh version


.SH EXAMPLE
.PP
.RS

.nf
$ gh issue create
$ gh repo clone cli/cli
$ gh pr checkout 321


.fi
.RE


.SH SEE ALSO
.PP
\fBgh\-alias(1)\fP, \fBgh\-api(1)\fP, \fBgh\-auth(1)\fP, \fBgh\-completion(1)\fP, \fBgh\-config(1)\fP, \fBgh\-gist(1)\fP, \fBgh\-issue(1)\fP, \fBgh\-pr(1)\fP, \fBgh\-release(1)\fP, \fBgh\-repo(1)\fP, \fBgh\-secret(1)\fP, \fBgh\-ssh\-key(1)\fP
