kind: ServiceAccount
apiVersion: v1
metadata:
  name: kubetail-cli
  namespace: kubetail-system
  labels:
    app.kubernetes.io/name: "kubetail"
    app.kubernetes.io/version: "0.9.2"
    app.kubernetes.io/instance: "kubetail"
    app.kubernetes.io/component: "cli"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail-cli
  labels:
    app.kubernetes.io/name: "kubetail"
    app.kubernetes.io/version: "0.9.2"
    app.kubernetes.io/instance: "kubetail"
    app.kubernetes.io/component: "cli"
rules:
- apiGroups: [""]
  resources: [pods/log]
  verbs: [list, watch]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail-cli
  labels:
    app.kubernetes.io/name: "kubetail"
    app.kubernetes.io/version: "0.9.2"
    app.kubernetes.io/instance: "kubetail"
    app.kubernetes.io/component: "cli"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubetail-cli
subjects:
- kind: ServiceAccount
  name: kubetail-cli
  namespace: kubetail-system
