LINUX_EXTENSIONS += install-module-symvers

define LINUX_MODULE_SYMVERS_INSTALL_FILE
	mkdir -p $(TARGET_DIR)/lib/modules/$(LINUX_VERSION_PROBED)
	cp $(LINUX_DIR)/Module.symvers $(TARGET_DIR)/lib/modules/$(LINUX_VERSION_PROBED)/
endef
LINUX_TARGET_FINALIZE_HOOKS += LINUX_MODULE_SYMVERS_INSTALL_FILE
