# vim: ts=2 sts=2 sw=2 et ft=sh
# Maintainer: Matt Rickard <mrick@google.com>
# THIS FILE IS AUTOGENERATED
# 
# PLEASE EDIT https://github.com/kubernetes/minikube/blob/master/hack/jenkins/release_update_releases_json.sh

pkgname=minikube
pkgver=0.15.0
pkgrel=1
pkgdesc="Minikube is a tool that makes it easy to run Kubernetes locally"
url="https://github.com/kubernetes/minikube"
license=('Apache')
arch=('x86_64')
depends=(
  'net-tools'
)
optdepends=(
  'kubectl-bin: to manage the cluster'
  'virtualbox'
  'docker-machine-kvm'
)
makedepends=()

source=(minikube_$pkgver::https://storage.googleapis.com/minikube/releases/v$pkgver/minikube-linux-amd64)
sha512sums=('d41f36bb5f47225754431abdd0e066b509b780c4231e27f19649c86cf3dc3f7e6eea46461c5629f557ff18043faef193555057c3af302db5a82867d4d9d4ab6c')

package() {
  cd "$srcdir"
  install -d "$pkgdir/usr/bin"
  install -m755 minikube_$pkgver "$pkgdir/usr/bin/minikube"
}
