name: "dependabot-gomodtidy"
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths:
      - "go.mod"
      - "go.sum"

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-gomodtidy:
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.head.repo.full_name == 'kubernetes/minikube'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        timeout-minutes: 1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.MINIKUBE_BOT_PAT }}

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        timeout-minutes: 1
        with:
          go-version-file: 'go.mod'

      - name: Run make gomodtidy
        timeout-minutes: 2
        run: |
          make gomodtidy
          if [[ -n $(git status --porcelain) ]]; then
            git config --global user.name "minikube-bot"
            git config --global user.email "20374350+minikube-bot@users.noreply.github.com"
            git add .
            git commit -m "update go.mod and go.sum"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          fi
