name: Lint
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'site/**'
  push:
    branches: [ master ]
    paths-ignore:
      - 'site/**'

# Limit one unit test job running per PR/Branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  # For example, if you push multiple commits to a pull request in quick succession, only the latest workflow run will continue
  cancel-in-progress: true
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.26.2'
permissions:
  contents: read
jobs:
    Lint:
        runs-on: ubuntu-22.04
        steps:
        - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
          timeout-minutes: 1
        - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
          timeout-minutes: 1
          with:
            go-version: ${{env.GO_VERSION}}
            cache: true      
        - name: Download Dependencies
          timeout-minutes: 1
          run: go mod download
        # needed because pkg/drivers/kvm/domain.go:28:2:
        - name: Install libvirt (Linux)
          timeout-minutes: 2
          if: runner.os == 'Linux'
          run: |
              sudo apt-get update              
              sudo apt-get install -y libvirt-dev
        - name: Lint
          timeout-minutes: 13
          env:
            TESTSUITE: lint
          run: make test
          continue-on-error: false
    Boilerplate:
        runs-on: ubuntu-22.04
        steps:
        - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
          timeout-minutes: 1
        - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
          timeout-minutes: 1
          with:
            go-version: ${{env.GO_VERSION}}
            cache: true  
        - name: Boilerplate check
          timeout-minutes: 1
          env:
            TESTSUITE: boilerplate
          run: make test
          continue-on-error: false
    Housekeeping:
       runs-on: ubuntu-22.04
       steps:
        - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
          timeout-minutes: 1
        - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
          timeout-minutes: 1
          with:
            go-version: ${{env.GO_VERSION}}
            cache: true
        - name: Install goimports
          timeout-minutes: 1
          run: go install golang.org/x/tools/cmd/goimports@latest
        - name: Verify go mod tidy
          timeout-minutes: 1
          run: |
            make gomodtidy
            if ! git diff-index --quiet HEAD; then
              git --no-pager diff
              echo "::notice::Please run 'make gomodtidy' and commit the changes"
              exit 1
            fi
        - name: Verify make fmt
          timeout-minutes: 1
          run: |
            make fmt
            if ! git diff-index --quiet HEAD; then
              git --no-pager diff
              echo "::notice::Please run 'make fmt' and commit the changes"
              exit 1
            fi
        - name: Verify make imports
          timeout-minutes: 1
          run: |
            make imports
            if ! git diff-index --quiet HEAD; then
              git --no-pager diff
              echo "::notice::Please run 'make imports' and commit the changes"
              exit 1
            fi
        - name: Install markdownlint
          timeout-minutes: 1
          run: npm install -g markdownlint-cli
        - name: Verify make mdlint
          timeout-minutes: 1
          run: make mdlint

