name: "publish image benchmark"
on:
  workflow_dispatch:
  schedule:
    # every day at 7am & 7pm pacific
    - cron: "0 2,14 * * *"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.26.2'
permissions:
  contents: read

jobs:
  image-benchmark:
    if: github.repository == 'kubernetes/minikube'
    runs-on: ubuntu-22.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-west-1'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Run Benchmark
        run: |
          ./hack/benchmark/image-build/publish-chart.sh

  
