name: "time-to-k8s benchmark"
on:
  workflow_dispatch:
  release:
    types: [released]
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.26.2'
permissions:
  contents: read

jobs:
  benchmark:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Checkout submodules
        run: git submodule update --init
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version: ${{env.GO_VERSION}}
      - name: time-to-k8s Benchmark
        id: timeToK8sBenchmark
        run: |
          ./hack/benchmark/time-to-k8s/time-to-k8s.sh
          echo "version=$(minikube version --short)" >> "$GITHUB_OUTPUT"
      - name: Create PR
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: add time-to-k8s benchmark for ${{ steps.timeToK8sBenchmark.outputs.version }}
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: addTimeToK8s${{ steps.timeToK8sBenchmark.outputs.version }}
          branch-suffix: short-commit-hash
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: "site: Add time-to-k8s benchmark for ${{ steps.timeToK8sBenchmark.outputs.version }} (Post-release)"
          body: Updating time-to-k8s benchmark as part of the release process
