name: "update-portainer-version"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 1"
permissions:
  contents: read

jobs:
  bump-portainer-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: portainer
      title: "Addon portainer: Update portainer image from {OLD_VERSION} to {NEW_VERSION}"
      labels: ok-to-test
      release-url: https://github.com/portainer/portainer
      workflow-file: update-portainer-version.yml
    secrets: inherit
