name: "update-ingress-version"
on:
  workflow_dispatch:
  schedule:
    # every Saturday at 1:00 Pacific/8:00 UTC
    - cron: "0 8 * * 6"
permissions:
  contents: read

jobs:
  bump-ingress-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: ingress
      title: "Addon ingress: Update ingress-nginx/controller image from {OLD_VERSION} to {NEW_VERSION}"
      labels: ok-to-test
      release-url: https://github.com/kubernetes/ingress-nginx
      workflow-file: update-ingress-version.yml
    secrets: inherit
