name: "update-runc-version"
on:
  workflow_dispatch:
  schedule:
    # every Tuesday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 2"
permissions:
  contents: read

jobs:
  bump-runc-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: runc
      title: "Kicbase/ISO: Update runc from {OLD_VERSION} to {NEW_VERSION}"
      branch-suffix: short-commit-hash
      release-url: https://github.com/opencontainers/runc/releases
      ok-to-build-image: true
      ok-to-build-iso: true
      workflow-file: update-runc-version.yml
    secrets: inherit
