name: "update-crictl-version"
on:
  workflow_dispatch:
  # Uncomment after crictl/cri-o issue resolved: https://github.com/kubernetes/minikube/issues/18359
  # schedule:
    # every Wednesday at around 3 am pacific/10 am UTC
    # - cron: "0 10 * * 3"
permissions:
  contents: read

jobs:
  bump-crictl-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: crictl
      title: "Kicbase/ISO: Update crictl from {OLD_VERSION} to {NEW_VERSION}"
      branch-suffix: short-commit-hash
      ok-to-build-image: true
      ok-to-build-iso: true
      workflow-file: update-crictl-version.yml
    secrets: inherit
