name: "update-docsy-version"
on:
  workflow_dispatch:
  schedule:
    # every Saturday at 1:00 Pacific/8:00 UTC
    - cron: "0 8 * * 6"
permissions:
  contents: read

jobs:
  bump-docsy-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      update-cmd: make update-docsy-version
      title: "site: Update docsy version to {NEW_VERSION}"
      branch: auto_bump_docsy_version
      release-url: https://github.com/google/docsy/releases
      workflow-file: update-docsy-version.yml
    secrets: inherit
