name: "update-docker-version"
on:
  workflow_dispatch:
  schedule:
    # every Thursday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 4"
permissions:
  contents: read

jobs:
  bump-docker-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: docker
      title: "Kicbase/ISO: Update docker from {OLD_VERSION} to {NEW_VERSION}"
      branch-suffix: short-commit-hash
      release-url: https://github.com/moby/moby/releases
      ok-to-build-image: true
      ok-to-build-iso: true
      workflow-file: update-docker-version.yml
    secrets: inherit
