name: "update-buildkit-version"
on:
  workflow_dispatch:
  schedule:
    # every Wednesday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 3"
permissions:
  contents: read

jobs:
  bump-buildkit-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: buildkit
      title: "Kicbase/ISO: Update buildkit from {OLD_VERSION} to {NEW_VERSION}"
      branch-suffix: short-commit-hash
      release-url: https://github.com/moby/buildkit/releases
      ok-to-build-image: true
      ok-to-build-iso: true
      workflow-file: update-buildkit-version.yml
    secrets: inherit
