name: "update-kong-version"
on:
  workflow_dispatch:
  schedule:
    # every Saturday at 1:00 Pacific/8:00 UTC
    - cron: "0 8 * * 6"
permissions:
  contents: read

jobs:
  bump-kong-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: kong
      title: "Addon kong: Update kong image from {OLD_VERSION} to {NEW_VERSION}"
      labels: ok-to-test
      release-url: https://github.com/Kong/kong
      workflow-file: update-kong-version.yml
    secrets: inherit
