name: "update-kubeadm-constants"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around midnight pacific/7 am UTC
    - cron: "0 6 * * 1"
permissions:
  contents: read

jobs:
  bump-k8s-versions:
    uses: ./.github/workflows/update-dependency.yml
    with:
      update-cmd: make update-kubeadm-constants
      title: "build: Bump kubeadm constants for kubernetes images"
      branch: auto_bump_kubeadm_constants
      workflow-file: update-kubeadm-constants.yml
    secrets: inherit
