name: "update-all"
on:
  workflow_dispatch:
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.26.2'
permissions:
  contents: read
jobs:
  update-all:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        timeout-minutes: 1
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        timeout-minutes: 1
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Bump versions
        id: bumpVersions
        timeout-minutes: 3
        run: |
          MAKEALL_OUTPUT=$(make _update-all)
          echo "changes<<EOF" >> "$GITHUB_OUTPUT"
          echo "$MAKEALL_OUTPUT" >> "$GITHUB_OUTPUT"
          echo "$(git status --porcelain)" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Create PR
        id: createPR
        if: ${{ steps.bumpVersions.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        timeout-minutes: 2
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: 'Kicbase/ISO: Update dependency versions'
          committer: minikube-bot <20374350+minikube-bot@users.noreply.github.com>
          author: minikube-bot <20374350+minikube-bot@users.noreply.github.com>
          branch: bump_iso_image_versions
          branch-suffix: short-commit-hash
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'chore: (debug pr) update all dependencies'
          body: |
            Changelog:
            ${{ steps.bumpVersions.outputs.changes }}
