name: "update-headlamp-version"
on:
  workflow_dispatch:
  schedule:
    # every Saturday at 1:00 Pacific/8:00 UTC
    - cron: "0 8 * * 6"
permissions:
  contents: read

jobs:
  bump-headlamp-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: headlamp
      title: "Addon Headlamp: Update Headlamp image from {OLD_VERSION} to {NEW_VERSION}"
      labels: ok-to-test
      release-url: https://github.com/headlamp-k8s/headlamp
      workflow-file: update-headlamp-version.yml
    secrets: inherit
