name: "update-cri-o-version"
on:
  workflow_dispatch:
  # Uncomment after crictl/cri-o issue resolved: https://github.com/kubernetes/minikube/issues/18359
  # schedule:
    # every Friday at around 3 am pacific/10 am UTC
    # - cron: "0 10 * * 5"
permissions:
  contents: read

jobs:
  bump-cri-o-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: cri-o
      title: "Kicbase/ISO: Update cri-o from {OLD_VERSION} to {NEW_VERSION}"
      branch-suffix: short-commit-hash
      ok-to-build-image: true
      ok-to-build-iso: true
      workflow-file: update-cri-o-version.yml
    secrets: inherit
