name: "update-kindnetd-version"
on:
  workflow_dispatch:
  schedule:
    # every Saturday at 1:00 Pacific/8:00 UTC
    - cron: "0 8 * * 6"
permissions:
  contents: read

jobs:
  bump-kindnetd-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: kindnetd
      title: "CNI: Update kindnetd from {OLD_VERSION} to {NEW_VERSION}"
      labels: ok-to-test
      workflow-file: update-kindnetd-version.yml
    secrets: inherit
