name: "update-metrics-server-version"
on:
  workflow_dispatch:
  schedule:
    # every Saturday at 1:00 Pacific/8:00 UTC
    - cron: "0 8 * * 6"
permissions:
  contents: read

jobs:
  bump-metrics-server-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: metrics-server
      title: "Addon metrics-server: Update metrics-server/metrics-server image from {OLD_VERSION} to {NEW_VERSION}"
      branch: auto_bump_metrics_server_version
      labels: ok-to-test
      release-url: https://github.com/kubernetes-sigs/metrics-server
      workflow-file: update-metrics-server-version.yml
    secrets: inherit
