name: "update-amd-gpu-device-plugin-version"
on:
  workflow_dispatch:
  schedule:
    # every Saturday at 1:00 Pacific/8:00 UTC
    - cron: "0 8 * * 6"
permissions:
  contents: read

jobs:
  bump-amd-gpu-device-plugin-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: amd-device-gpu-plugin
      update-cmd: make update-amd-device-plugin-version
      title: "Addon amd-gpu-device-plugin: Update amd/k8s-device-plugin image from {OLD_VERSION} to {NEW_VERSION}"
      branch: auto_bump_amd_device_plugin_version
      labels: ok-to-test
      release-url: https://github.com/ROCm/k8s-device-plugin
      workflow-file: update-amd-gpu-device-plugin-version.yml
    secrets: inherit
