name: "update-all"
on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  update-all:
    uses: ./.github/workflows/update-dependency.yml
    with:
      update-cmd: make _update-all
      title: "chore: (debug pr) update all dependencies"
      commit-message: "Kicbase/ISO: Update dependency versions"
      branch: bump_iso_image_versions
      branch-suffix: short-commit-hash
      workflow-file: update-all.yml
    secrets: inherit
