name: "update-kong-ingress-controller-version"
on:
  workflow_dispatch:
  schedule:
    # every Saturday at 1:00 Pacific/8:00 UTC
    - cron: "0 8 * * 6"
permissions:
  contents: read

jobs:
  bump-kong-ingress-controller-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: kong-ingress-controller
      title: "Addon kong: Update kong/kubernetes-ingress-controller image from {OLD_VERSION} to {NEW_VERSION}"
      branch: auto_bump_kong_ingress_controller_version
      labels: ok-to-test
      release-url: https://github.com/Kong/kubernetes-ingress-controller
      workflow-file: update-kong-ingress-controller-version.yml
    secrets: inherit
