name: "update-golang-versions"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 2 am pacific/9 am UTC
    - cron: "0 9 * * 1"
permissions:
  contents: read

jobs:
  bump-golang-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: golang
      update-cmd: make update-golang-version GOTOOLCHAIN=auto
      title: "build: Update go from {OLD_VERSION} to {NEW_VERSION}"
      commit-message: "Update go from {OLD_VERSION} to {NEW_VERSION}"
      branch-suffix: short-commit-hash
      release-url: https://github.com/kubernetes/kubernetes/blob/master/build/build-image/cross/VERSION
      ok-to-build-image: true
      workflow-file: update-golang-version.yml
    secrets: inherit
