name: "update-golint-version"
on:
  workflow_dispatch:
  schedule:
    # every Saturday at 1:00 Pacific/8:00 UTC
    - cron: "0 8 * * 6"
permissions:
  contents: read

jobs:
  bump-golint-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: golint
      title: "CI: Update golint from {OLD_VERSION} to {NEW_VERSION}"
      release-url: https://github.com/golangci/golangci-lint/releases
      workflow-file: update-golint-version.yml
    secrets: inherit
