name: "update-gotestsum-version"
on:
  workflow_dispatch:
  schedule:
    # every Saturday at 1:00 Pacific/8:00 UTC
    - cron: "0 8 * * 6"
permissions:
  contents: read

jobs:
  bump-gotestsum-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: gotestsum
      title: "CI: Update gotestsum from {OLD_VERSION} to {NEW_VERSION}"
      release-url: https://github.com/gotestyourself/gotestsum/releases
      workflow-file: update-gotestsum-version.yml
    secrets: inherit
