name: "update-cri-dockerd-version"
on:
  workflow_dispatch:
  schedule:
    # every Saturday at 1:00 Pacific/8:00 UTC
    - cron: "0 8 * * 6"
permissions:
  contents: read

jobs:
  bump-cri-dockerd-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: cri-dockerd
      title: "Kicbase/ISO: Update cri-dockerd from {OLD_VERSION} to {NEW_VERSION}"
      branch: auto_bump_cri_dockerd_version
      release-url: https://github.com/Mirantis/cri-dockerd
      ok-to-build-image: true
      ok-to-build-iso: true
      workflow-file: update-cri-dockerd-version.yml
    secrets: inherit
