name: "update-kubernetes-versions-list"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around midnight pacific/7 am UTC
    - cron: "0 6 * * 1"
permissions:
  contents: read

jobs:
  update-kubernetes-versions-list:
    uses: ./.github/workflows/update-dependency.yml
    with:
      update-cmd: make update-kubernetes-versions-list
      title: "build: Update Kubernetes versions list"
      branch: auto_update_kubernetes_versions_list
      workflow-file: update-kubernetes-versions-list.yml
    secrets: inherit
