name: "update-kubernetes-versions"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 1 am pacific/8 am UTC
    - cron: "0 8 * * 1"
permissions:
  contents: read

jobs:
  bump-k8s-versions:
    uses: ./.github/workflows/update-dependency.yml
    with:
      update-cmd: make update-kubernetes-version
      branch: auto_bump_k8s_versions
      labels: ok-to-test,kind/feature
      workflow-file: update-k8s-versions.yml
    secrets: inherit
