name: "update-gopogh-versions"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 2 am pacific/9 am UTC
    - cron: "0 9 * * 1"
permissions:
  contents: read

jobs:
  bump-gopogh-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: gopogh
      title: "CI: Update gopogh from {OLD_VERSION} to {NEW_VERSION}"
      release-url: https://github.com/medyagh/gopogh/releases
      workflow-file: update-gopogh-version.yml
    secrets: inherit
