name: "update-kubevirt-version"
on:
  workflow_dispatch:
  schedule:
    # every Saturday at 2:00 Pacific/9:00 UTC
    - cron: "0 9 * * 6"
permissions:
  contents: read

jobs:
  bump-kubevirt-version:
    uses: ./.github/workflows/update-dependency.yml
    with:
      dep: kubevirt
      title: "Addon kubevirt: Update KubeVirt version from {OLD_VERSION} to {NEW_VERSION}"
      labels: ok-to-test
      workflow-file: update-kubevirt-version.yml
    secrets: inherit
