name: "update-traefik-version"
on:
  workflow_dispatch:
  schedule:
    # 1st of every month at 8:00 UTC
    - cron: "0 8 1 * *"
env:
  GOPROXY: https://proxy.golang.org
permissions:
  contents: read

jobs:
  bump-traefik-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        timeout-minutes: 1
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        timeout-minutes: 2
        with:
          go-version-file: 'go.mod'
      - name: Bump Traefik version
        id: bumpTraefik
        timeout-minutes: 1
        run: |
          out=$(make update-traefik-version)
          echo "OLD_VERSION=$(echo "$out" | jq -r .old_version)" >> "$GITHUB_OUTPUT"
          echo "NEW_VERSION=$(echo "$out" | jq -r .new_version)" >> "$GITHUB_OUTPUT"
      - name: Create PR
        if: ${{ steps.bumpTraefik.outputs.OLD_VERSION != steps.bumpTraefik.outputs.NEW_VERSION }}
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        timeout-minutes: 1
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: 'Addon Traefik: Update Traefik helm chart from ${{ steps.bumpTraefik.outputs.OLD_VERSION }} to ${{ steps.bumpTraefik.outputs.NEW_VERSION }}'
          committer: minikube-bot <20374350+minikube-bot@users.noreply.github.com>
          author: minikube-bot <20374350+minikube-bot@users.noreply.github.com>
          branch: auto_bump_traefik_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Addon Traefik: Update Traefik helm chart from ${{ steps.bumpTraefik.outputs.OLD_VERSION }} to ${{ steps.bumpTraefik.outputs.NEW_VERSION }}'
          labels: ok-to-test
          body: |
            The [Traefik](https://github.com/traefik/traefik-helm-chart) project released a new helm chart version.

            This PR was auto-generated by `make update-traefik-version` using [update-traefik-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-traefik-version.yml) CI Workflow.
